### ISSUE TITLE
Webpack 4 support?

### ISSUE THREAD

**Issue by pavelloz** [agoldis/webpack-require-from#3]
Am i the only one having errors on webpack 4 even though on 3.11 its working fine?

Im getting `Error: __cdnUrl is not a function or not avialable at runtime`

I was using the plugin to get cdnUrl when application was running in the browser to load chunks from the correct environment - every env. has its own cdn.

Now im getting this error which is kind of weird.

Cheers

**Comment by agoldis** [comment]
Thanks for opening the issue! 
Can you please provide more details - what is your configuration? How can I reproduce the issue.

**Comment by pavelloz** [comment]
Hey,

I deleted the config already, but i copied it over from different project (working on 3.11) and it looks like this:

`webpack.config.babel.js`

```
import WebpackRequireFrom from 'webpack-require-from';
...
    new WebpackRequireFrom({
      methodName: '__cdnUrl'
    })
```

Then in our serverside layout code i placed:
```
<script>
  /* Set output.publicPath on runtime, to avoid hardcoding paths in env's or views */
  window.__cdnUrl = function() { return "{{ '' | asset_url }}" };
</script>
```

Which basically renders path to our cdn, ie. `https://uibsbuiosd79b329b98.cloudfront.com/test/page/assets/`

And everything works fine in 3.11 -- build goes through, when i go to the webpage chunks are loaded from `https://uibsbuiosd79b329b98.cloudfront.com/test/page/assets/chunkname.shahash.js`, but on 4.2 there is an error that i pasted above - this error is displayed once for every chunk/file.

**Comment by agoldis** [comment]
@pavelloz cool, i will try to run it with webpack 4 tonight and see what's going on

**Comment by agoldis** [comment]
@pavelloz I tried to reproduce the issue - but with no success.
I have created a few tests that check that the plugin works correctly with webpack 4 and 3 - those are only checking the basing webpack config.
May be you have some complex webpack configuration that prevents the plugin from works.

Anyways, I have implemented some changes to cope with webpack 4 deprecation messages and released a new version.

Aslo, see https://github.com/agoldis/webpack-require-from#troubleshooting. 

Please tell me if you're able to reproduce the issue though.

**Comment by pavelloz** [comment]
Since webpack 4 is now 0config ill try to prepare minimal case where the bug occurs if troubleshooting doesnt help :)

Thank you very much for your time

**Comment by pavelloz** [comment]
After reading troubleshooting

> Make sure the method is define the very first invocation of eithe require.ensure() or import()

This is what i think is wrong, because in webpack 3 i didnt have this method in javascripts at all.
I just didnt.

I have it defined inline in my html and `methodName` pointed in the webpack config, nothing in between. In the config quote above is everything i used both for webpack 3 (which works) and webpack 4 (which doesnt work)

**Comment by agoldis** [comment]
@pavelloz may be I need to rephrase the troubleshooting, having it configured inline in HTML should do the job. Did you have a chance to reproduce the issue?

**Comment by pavelloz** [comment]
I just created project from scratch, by hand, using only webpack-require-from and it works excellent on webpack 4.4 -- to sum up, i have something wrong in my project config :)

Thank you very much for your time.

**Comment by pavelloz** [comment]
Okay, so we know that plugin works, so maybe you will know what i might have broken :)

Thank you in advance

I tried troubleshooting, i tried disabling various plugins, setting and unsetting publicPath - so far no positive effect, heres the stack trace:

```
Error: WebpackRequireFrom: __ASSETS_PATH__ is not a function or not available at runtime. See https://github.com/agoldis/webpack-require-from#troubleshooting
    at Function.get [as p] (/Users/pavel/projects/test/node_modules/cache-loader/dist/cjs.js!/Users/pavel/projects/test/node_modules/css-loader/index.js!/Users/pavel/projects/test/node_modules/postcss-loader/lib/index.js!/Users/pavel/projects/test/node_modules/sass-loader/lib/loader.js!/Users/pavel/projects/test/src/styles/index.scss:72:21)
    at Object.module.exports.module.exports (/Users/pavel/projects/test/node_modules/cache-loader/dist/cjs.js!/Users/pavel/projects/test/node_modules/css-loader/index.js!/Users/pavel/projects/test/node_modules/postcss-loader/lib/index.js!/Users/pavel/projects/test/node_modules/sass-loader/lib/loader.js!/Users/pavel/projects/test/src/styles/index.scss:109:38)
    at __webpack_require__ (/Users/pavel/projects/test/node_modules/cache-loader/dist/cjs.js!/Users/pavel/projects/test/node_modules/css-loader/index.js!/Users/pavel/projects/test/node_modules/postcss-loader/lib/index.js!/Users/pavel/projects/test/node_modules/sass-loader/lib/loader.js!/Users/pavel/projects/test/src/styles/index.scss:21:30)
    at Object.<anonymous> (/Users/pavel/projects/test/node_modules/cache-loader/dist/cjs.js!/Users/pavel/projects/test/node_modules/css-loader/index.js!/Users/pavel/projects/test/node_modules/postcss-loader/lib/index.js!/Users/pavel/projects/test/node_modules/sass-loader/lib/loader.js!/Users/pavel/projects/test/src/styles/index.scss:411:17998)
    at __webpack_require__ (/Users/pavel/projects/test/node_modules/cache-loader/dist/cjs.js!/Users/pavel/projects/test/node_modules/css-loader/index.js!/Users/pavel/projects/test/node_modules/postcss-loader/lib/index.js!/Users/pavel/projects/test/node_modules/sass-loader/lib/loader.js!/Users/pavel/projects/test/src/styles/index.scss:21:30)
    at module.exports.module.exports (/Users/pavel/projects/test/node_modules/cache-loader/dist/cjs.js!/Users/pavel/projects/test/node_modules/css-loader/index.js!/Users/pavel/projects/test/node_modules/postcss-loader/lib/index.js!/Users/pavel/projects/test/node_modules/sass-loader/lib/loader.js!/Users/pavel/projects/test/src/styles/index.scss:84:18)
    at Object.<anonymous> (/Users/pavel/projects/test/node_modules/cache-loader/dist/cjs.js!/Users/pavel/projects/test/node_modules/css-loader/index.js!/Users/pavel/projects/test/node_modules/postcss-loader/lib/index.js!/Users/pavel/projects/test/node_modules/sass-loader/lib/loader.js!/Users/pavel/projects/test/src/styles/index.scss:87:10)
    at Module._compile (/Users/pavel/projects/test/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.exec (/Users/pavel/projects/test/node_modules/webpack/lib/NormalModule.js:162:12)
    at childCompiler.runAsChild (/Users/pavel/projects/test/node_modules/extract-text-webpack-plugin/dist/loader.js:140:25)
    at compile (/Users/pavel/projects/test/node_modules/webpack/lib/Compiler.js:240:11)
    at hooks.afterCompile.callAsync.err (/Users/pavel/projects/test/node_modules/webpack/lib/Compiler.js:485:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pavel/projects/test/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pavel/projects/test/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/pavel/projects/test/node_modules/webpack/lib/Compiler.js:482:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pavel/projects/test/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pavel/projects/test/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/pavel/projects/test/node_modules/webpack/lib/Compilation.js:964:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pavel/projects/test/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pavel/projects/test/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/pavel/projects/test/node_modules/webpack/lib/Compilation.js:955:32)
    at _err0 (eval at create (/Users/pavel/projects/test/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at /Users/pavel/projects/test/node_modules/uglifyjs-webpack-plugin/dist/index.js:266:11
    at _class.runTasks (/Users/pavel/projects/test/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:63:9)
    at UglifyJsPlugin.optimizeFn (/Users/pavel/projects/test/node_modules/uglifyjs-webpack-plugin/dist/index.js:186:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pavel/projects/test/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pavel/projects/test/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/Users/pavel/projects/test/node_modules/webpack/lib/Compilation.js:950:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pavel/projects/test/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pavel/projects/test/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/Users/pavel/projects/test/node_modules/webpack/lib/Compilation.js:946:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pavel/projects/test/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/pavel/projects/test/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/pavel/projects/test/node_modules/webpack/lib/Compilation.js:888:27)
    at hooks.make.callAsync.err (/Users/pavel/projects/test/node_modules/webpack/lib/Compiler.js:479:17)
    at _err0 (eval at create (/Users/pavel/projects/test/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/Users/pavel/projects/test/node_modules/webpack/lib/Compilation.js:756:12)
    at processModuleDependencies.err (/Users/pavel/projects/test/node_modules/webpack/lib/Compilation.js:695:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by pavelloz** [comment]
I found the issue in a place where i wasnt expecting - the error occurs when i import scss file in my js file, which is weird to say the least.

`import '../styles/index.scss';` <- problematic line

**Comment by agoldis** [comment]
@pavelloz no problem, would you mind sharing your files for reproducing? I want to reproduce and understand what is the root cause - it is weird that importing fonts affects the plugin 🤔

**Comment by agoldis** [comment]
@pavelloz the error you've got - was it at runtime or while building your project?

**Comment by agoldis** [comment]
From the stack trace you have submitted, it seems like the following happens:
* your `scss` file has an `import` statement
* the import statement is passed through `sass-loader` > `postcss-loader` > `css-loader`
* `css-loader` uses [`loader-utils`](https://github.com/webpack/loader-utils/blob/master/lib/isUrlRequest.js#L8) to decide whether it's local file or URL that needs to be fetched from remote resource
* the import is considered as an URL, so webpack's remote loading utility is activated
* `extract-text-webpack-plugin` causes the the contents to be pushed on the top of the page, before your inline HTML is defined

**Comment by agoldis** [comment]
@pavelloz would it be useful to have the function body provided as part of configuration? e.g.

```
...
plugins: {
    new WebpackRequireFrom({
      methodBody: 'function getURL() { return "https://whateva"; }'
    })
}
...
```

**Comment by pavelloz** [comment]
1. Error was on building the project
2. I will try to describe it as good as i can.
My input directory structure look like this (this is output of tree with unnecessary stuff cut out):

```
src
├── fonts
│   └── proxima-nova
│       ├── 35F696_0_0.woff
│       └── 35F696_0_0.woff
...
├── images
├── scripts
│   └── index.js
└── styles
    ├── general
    │   └── _fonts.scss
    └── index.scss
```

And when output files land in directory they are all in the same directory, lets call it `dist/autogenerated`.

It goes something like this:

```
marketplace_builder/assets
└── autogenerated
    ├── 35F696_14_0.2bf4e69f.woff
    ├── 35F696_14_0.d1d7d3f2.woff2
    ...
    ├── common.css <-- references to fonts
    ├── common.css.map
    ├── common.js <--- this is index.js
    ├── common.js.map
```

And paths look like this `../fonts/proxima-nova/35F696_2_0.woff` because relative to index.scss fonts are located in above dir and `fonts/`. 

Im using file-loader to load them with those settings:
```js
{
        test: /\.(eot|ttf|woff|woff2)(\?.+)?$/,
        use: [{ loader: 'file-loader',  options: {
      name: '[name].[hash:8].[ext]',
      publicPath: '.'
    }]     
}
```

3. I think having the function with its body defined in the config wouldn't help me, because the content of return string is known only in the browser at the runtime - i have it inlined in html because my server fills this variable during rendering of the page (we have 3 different variants depending on environment using)

**Comment by agoldis** [comment]
@pavelloz thanks for your responses and providing the example. 
I will try to reproduce the problem and find a way to mitigate it.
